server:
  port: 2003
spring:
  application:
    name: seata-account
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#      config:
#        server-addr: localhost:8848
    alibaba:
      seata:
        tx-service-group: default_tx_group
        service:
          vgroup-mapping: default
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/seata_account?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&serverTimezone=UTC
    username: root
    password: root


mybatis:
  mapper-locations: classpath:mapper/**.xml
